# Generated by Django 4.0.5 on 2022-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fio',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.CharField(default='Job title', max_length=50),
        ),
    ]
